org: jschuur
app: videos-learnchinese-club
service: videos-learnchinese-club

plugins:
  - serverless-webpack
  - serverless-dotenv-plugin
  - serverless-offline-dotenv
  - serverless-offline
  - serverless-domain-manager
  - serverless-prune-plugin

package:
  individually: true
  excludeDevDependencies: true
  browser: false

custom:
  stage: ${opt:stage, self:provider.stage}
  # serverless-offline:
  #   useChildProcesses: true
  domains:
    prod: api.learnchinese.club
    dev: api-dev.learnchinese.club
  domain: ${self:custom.domains.${self:custom.stage}}
  customDomain:
    domainName: ${self:custom.domains.${self:custom.stage}}
    basePath: 'v1'
    stage: ${self:custom.stage}
    certificateName: '*.learnchinese.club'
    createRoute53Record: true
  prune:
    automatic: true
    number: 3

provider:
  name: aws
  runtime: nodejs12.x

functions:
  getVideos:
    handler: server/api/videos.getVideos
    events:
      - http:
          path: videos
          method: get
          cors: true

  deleteVideo:
    handler: server/api/videos.deleteVideo
    events:
      - http:
          path: videos/
          method: delete
          cors: true

  getChannels:
    handler: server/api/channels.getChannels
    events:
      - http:
          path: channels
          method: get
          cors: true

  addChannel:
    handler: server/api/channels.addChannel
    events:
      - http:
          path: channels
          method: post
          cors: true

  status:
    handler: server/api/status.getStatus
    events:
      - http:
          path: status/
          method: get

  update_videos:
    handler: server/schedule.updateVideos
    timeout: 30
    events:
      - schedule: cron(25,55 * * * ? *)

  update_videos_longtail:
    handler: server/schedule.updateVideosLongTail
    timeout: 30
    events:
      - schedule: cron(10 0 * * ? *)

  update_channels:
    handler: server/schedule.updateChannels
    timeout: 60
    events:
      - schedule: rate(6 hours)
