service: videos-learnchinese-club

plugins:
  # - serverless-bundle
  - serverless-webpack
  - serverless-dotenv-plugin
  - serverless-offline-dotenv
  - serverless-offline
  - serverless-domain-manager

package:
  individually: true
  excludeDevDependencies: true
  browser: false

custom:
  stage: ${opt:stage, self:provider.stage}
  serverless-offline:
    useChildProcesses: true
  client:
    distributionFolder: site/public
    bucketName: club.learnchinese.videos
  domains:
    prod: data.learnchinese.club
    stage: data-stage.learnchinese.club
    dev: data-dev.learnchinese.club
  domain: ${self:custom.domains.${self:custom.stage}}
  customDomain:
    domainName: ${self:custom.domains.${self:custom.stage}}
    basePath: 'v1'
    stage: ${self:custom.stage}
    certificateName: '*.learnchinese.club'
    createRoute53Record: true

provider:
  name: aws
  runtime: nodejs12.x

functions:
  videos:
    handler: server/api/videos.get
    events:
      - http:
          path: videos
          method: get
          cors: true

  channels:
    handler: server/api/channels.post
    events:
      - http:
          path: channels
          method: post
          cors: true

  status:
    handler: server/api/status.handler
    events:
      - http:
          path: status/
          method: get

  update_videos:
    handler: server/update.videos
    timeout: 30
    events:
      - schedule: rate(60 minutes)

  update_channels:
    handler: server/update.channels
    timeout: 60
    events:
      - schedule: rate(6 hours)
