name: Backup MongoDB

on:
  schedule:
    - cron: '0 0 * * *'

env:
  AWS_ACCESS_KEY_ID: ${{ secrets.AWS_ACCESS_KEY_ID }}
  AWS_SECRET_ACCESS_KEY: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
  AWS_DEFAULT_REGION: ${{ secrets.AWS_DEFAULT_REGION }}
  AWS_BACKUP_DESTINATION: ${{ secrets.AWS_BACKUP_DESTINATION }}
  MONGODB_URL_BACKUP: ${{ secrets.MONGODB_URL_BACKUP }}

jobs:
  backup_mongo_db:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2

      - name: Set up Node
        uses: actions/setup-node@v1
        with:
          node-version: '12.x'

      - name: Install dependencies
        run: sudo apt-get install awscli

      - name: Execute backup script
        run: npm run backup:prod
