name: Rebuild Gatsby site

on:
  schedule:
    - cron: '*/30 * * * *'
  push:
    branches:
      - production
  repository_dispatch:

env:
  NETLIFY_SITE_ID: ${{ secrets.NETLIFY_SITE_ID }}
  NETLIFY_AUTH_TOKEN: ${{ secrets.NETLIFY_AUTH_TOKEN }}
  MONGODB_URL: ${{ secrets.MONGODB_URL }}

jobs:
  rebuild:
    name: Rebuild Gatsby Site
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v2
        with:
          ref: 'production'

      - name: Set up Node
        uses: actions/setup-node@v1
        with:
          node-version: '12.x'

      - name: Update dependencies
        run: npm install
        working-directory: site

      - name: Build site
        run: npm run build
        working-directory: site

      - name: Deploy site
        run: npm run deploy
        working-directory: site
