name: Redeploy Gatsby site

on:
  schedule:
    - cron: '*/30 * * * *'
  push:
    branches:
      - production

env:
  AWS_ACCESS_KEY_ID: ${{ secrets.AWS_ACCESS_KEY_ID }}
  AWS_SECRET_ACCESS_KEY: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
  MONGODB_URL: ${{ secrets.MONGODB_URL }}
  MONGODB_HOST: ${{ secrets.MONGODB_HOST }}
  MONGODB_USER: ${{ secrets.MONGODB_USER }}
  MONGODB_PASSWORD: ${{ secrets.MONGODB_PASSWORD }}
  MONGODB_DATABASE: ${{ secrets.MONGODB_DATABASE }}
  MONGODB_REPLICASET: ${{ secrets.MONGODB_REPLICASET }}

jobs:
  rebuild:
    name: Rebuild Gatsby Site
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v2
        with:
          ref: 'production'

      - name: Set up Node
        uses: actions/setup-node@v1
        with:
          node-version: '12.x'

      - name: Install dependencies
        run: npm install
        working-directory: site

      - name: Build site
        run: npm run build
        working-directory: site

      - name: Deploy site
        run: npm run deploy
        working-directory: site
